services:
  portainer:
    image: portainer/portainer-ce:2.39.4
    container_name: portainer
    restart: always
    command: ["-H", "tcp://socket-proxy:2375"]
    ports:
      - "127.0.0.1:9000:9000"
    volumes:
      - portainer_data:/data

    networks:
      - proxy_net
      - socket_proxy_net

    security_opt:
      - no-new-privileges:true

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`portainer.${BASE_DOMAIN}`)"
      - "traefik.http.routers.portainer.entrypoints=websecure"
      - "traefik.http.routers.portainer.tls=true"
      - "traefik.http.routers.portainer.tls.certresolver=letsencrypt"
      - "traefik.http.routers.portainer.tls.domains[0].main=*.${BASE_DOMAIN}"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
      - "traefik.docker.network=proxy_net"

      - "traefik.http.middlewares.portainer-ipallowlist.ipallowlist.sourcerange=192.168.1.0/24"
      - "traefik.http.routers.portainer.middlewares=portainer-ipallowlist"

networks:
  proxy_net:
    external: true
  socket_proxy_net:
    external: true

volumes:
  portainer_data:

