services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:2.4.0
    container_name: prowlarr
#    user: "1000:1000"

    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}

    volumes:
      - ./config/data:/config

    networks:
      - internal_media_net
      - proxy_net

    restart: unless-stopped

    security_opt:
      - no-new-privileges:true

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prowlarr.rule=Host(`prowlarr.${BASE_DOMAIN}`)"
      - "traefik.http.routers.prowlarr.entrypoints=websecure"
      - "traefik.http.routers.prowlarr.tls=true"
      - "traefik.http.routers.prowlarr.tls.certresolver=letsencrypt"
      - "traefik.http.routers.prowlarr.tls.domains[0].main=*.${BASE_DOMAIN}"
      - "traefik.http.services.prowlarr.loadbalancer.server.port=9696"
      - "traefik.docker.network=proxy_net"

      - "traefik.http.middlewares.prowlarr-ipallowlist.ipallowlist.sourcerange=192.168.1.0/24"
      - "traefik.http.routers.prowlarr.middlewares=prowlarr-ipallowlist"

      - "homepage.group=Descargas"
      - "homepage.name=Prowlarr"
      - "homepage.icon=prowlarr.png"
      - "homepage.href=https://prowlarr.${BASE_DOMAIN}"
      - "homepage.description=Gestor de indexers para Sonarr y Radarr"

networks:
  proxy_net:
    external: true
  internal_media_net:
    external: true