services:
  cups:
    image: ydkn/cups@sha256:76eb4fcc9bfce7573787938d9257cfced5dd21064559eae4ce112aa6a9d13ac2
    container_name: cups
    restart: unless-stopped

    ports:
      - 631:631

    devices:
      - /dev/bus/usb:/dev/bus/usb

    volumes:
      - ./config/data:/etc/cups
      - ./config/cupsd.conf:/etc/cups/cupsd.conf
      - ./config/printers.conf.O:/etc/cups/printers.conf.O
      - ./config/printers.conf:/etc/cups/printers.conf

    environment:
      - ADMIN_PASSWORD=${CUPS_ADMIN_PASSWORD}
      - CUPS_SERVER=${SERVER_IP}:631

    security_opt:
      - no-new-privileges:true

    labels:
      - "homepage.group=Sistema"
      - "homepage.name=CUPS"
      - "homepage.icon=mdi-printer"
      - "homepage.href=https://${SERVER_IP}:631"
      - "homepage.description=Servidor de impresion"
