services:
  networks:
    image: alpine:3.24.1
    container_name: docker-networks-bootstrap
    command: ["sleep", "infinity"]

    security_opt:
      - no-new-privileges:true

    networks:
      - dns_net
      - proxy_net
      - internal_media_net
      - socket_proxy_net

networks:
  dns_net:
    name: dns_net
    driver: bridge

  proxy_net:
    name: proxy_net
    driver: bridge

  internal_media_net:
    name: internal_media_net
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/16

  socket_proxy_net:
    name: socket_proxy_net
    driver: bridge
    internal: true
