version: "3.9"

services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    # user: "1000:1000"

    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}

    volumes:
      - ./config/data:/config
      - ./tvseries:/tv
      - ./downloadclient-downloads:/downloads

    networks:
      - internal_media_net
      - proxy_net
    restart: unless-stopped

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sonarr.rule=Host(`sonarr.${BASE_DOMAIN}`)"
      - "traefik.http.routers.sonarr.entrypoints=websecure"
      - "traefik.http.routers.sonarr.tls=true"
      - "traefik.http.routers.sonarr.tls.certresolver=letsencrypt"
      - "traefik.http.routers.sonarr.tls.domains[0].main=*.${BASE_DOMAIN}"
      - "traefik.http.services.sonarr.loadbalancer.server.port=8989"
      - "traefik.docker.network=proxy_net"

      - "homepage.group=Descargas"
      - "homepage.name=Sonarr"
      - "homepage.icon=sonarr.png"
      - "homepage.href=https://sonarr.${BASE_DOMAIN}"
      - "homepage.description=Descarga y organizacion automatica de series"


networks:
  proxy_net:
    external: true
  internal_media_net:
    external: true
