network:
  version: 2
  renderer: networkd
  ethernets:
    eth0:
      optional: false
      dhcp4: false
      addresses:
        - __SERVER_IP__/24
      routes:
        - to: default
          via: 192.168.1.1
      nameservers:
        search: []
        addresses:
          - 8.8.8.8
          - 1.1.1.1
