services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    hostname: pihole
    restart: unless-stopped

    cap_add:
      - NET_ADMIN

    environment:
      TZ: ${TZ}
      FTLCONF_webserver_api_password: ${PIHOLE_WEBPASSWORD}
      FTLCONF_dns_listeningMode: "LOCAL"
      FTLCONF_misc_etc_dnsmasq_d: 'true'
      FTLCONF_dns_reply_host_IPv4: '${SERVER_IP}'
#      FTLCONF_dns_reply_host_IPv6: '2800:98:1612:1559:29da:bdf1:a823:bdf7'

    volumes:
      - ./etc-pihole:/etc/pihole
      - ./etc-dnsmasq.d:/etc/dnsmasq.d

    ports:
      - "${SERVER_IP}:53:53/tcp"
      - "${SERVER_IP}:53:53/udp"
#      - "8081:80/tcp"

    networks:
      - dns_net
      - proxy_net

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pihole.rule=Host(`pihole.${BASE_DOMAIN}`)"
      - "traefik.http.routers.pihole.entrypoints=websecure"
      - "traefik.http.routers.pihole.tls=true"
      - "traefik.http.routers.pihole.tls.certresolver=letsencrypt"
      - "traefik.http.routers.pihole.tls.domains[0].main=*.${BASE_DOMAIN}"
      - "traefik.http.services.pihole.loadbalancer.server.port=80"
      - "traefik.docker.network=proxy_net"

      - "traefik.http.middlewares.pihole-ipallowlist.ipallowlist.sourcerange=192.168.1.0/24"
      - "traefik.http.routers.pihole.middlewares=pihole-ipallowlist"

      - "homepage.group=Sistema"
      - "homepage.name=Pi-hole"
      - "homepage.icon=pi-hole.png"
      - "homepage.href=https://pihole.${BASE_DOMAIN}/admin"
      - "homepage.description=DNS y bloqueador de anuncios"

    healthcheck:
      test: ["CMD", "dig", "@127.0.0.1", "google.com"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  dns_net:
    external: true

  proxy_net:
    external: true
