version: "3.9"

services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: unless-stopped

    environment:
      - HOMEPAGE_ALLOWED_HOSTS=${BASE_DOMAIN}

    volumes:
      - ./config:/app/config

    networks:
      - proxy_net
      - socket_proxy_net

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homepage.rule=Host(`${BASE_DOMAIN}`)"
      - "traefik.http.routers.homepage.entrypoints=websecure"
      - "traefik.http.routers.homepage.tls=true"
      - "traefik.http.routers.homepage.tls.certresolver=letsencrypt"
      - "traefik.http.routers.homepage.tls.domains[0].main=${BASE_DOMAIN}"
      - "traefik.http.services.homepage.loadbalancer.server.port=3000"
      - "traefik.docker.network=proxy_net"

networks:
  proxy_net:
    external: true
  socket_proxy_net:
    external: true
